<a href="https://colab.research.google.com/github/qtuter1997/MachineLearning/blob/main/d2l/Preliminaries/Data%20Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Cheat sheet tensorflow 2.x**

From d2l

1.   Getting started
2.   Operations
3.   Broadcasting Machenism 
4.   Indexing and Slicing
5.   Saving memory
6.   Conversion to other Python Objects
7.   Summary
8.   Exercises





In [6]:
import numpy as np
import tensorflow as tf

tf.__version__

'2.4.1'

In [36]:
X = tf.constant([[1,9,3],[4,5,6]], dtype=float)
X

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 9., 3.],
       [4., 5., 6.]], dtype=float32)>

In [39]:
tf.argmax(X, axis=0)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 0, 1])>

In [33]:
tf.reduce_max(X)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [40]:
Y = tf.reshape(X,[3,2])
Y

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 9.],
       [3., 4.],
       [5., 6.]], dtype=float32)>

In [41]:
tf.argmax(Y)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([2, 0])>

In [43]:
Y.shape[1]

2